"""updating foreign key ondelete

Revision ID: 49538283cfb5
Revises: abc006aece23
Create Date: 2026-03-13 11:06:10.739541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49538283cfb5'
down_revision: Union[str, Sequence[str], None] = 'abc006aece23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_details_ibfk_1'), 'chat_details', type_='foreignkey')
    op.create_foreign_key(None, 'chat_details', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('chats_ibfk_1'), 'chats', type_='foreignkey')
    op.create_foreign_key(None, 'chats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('otp_registrasi_ibfk_1'), 'otp_registrasi', type_='foreignkey')
    op.create_foreign_key(None, 'otp_registrasi', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('otp_reset_password_ibfk_1'), 'otp_reset_password', type_='foreignkey')
    op.create_foreign_key(None, 'otp_reset_password', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('pipeline_logs_ibfk_1'), 'pipeline_logs', type_='foreignkey')
    op.create_foreign_key(None, 'pipeline_logs', 'chat_details', ['chat_detail_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_auth_ibfk_1'), 'user_auth', type_='foreignkey')
    op.create_foreign_key(None, 'user_auth', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_auth', type_='foreignkey')
    op.create_foreign_key(op.f('user_auth_ibfk_1'), 'user_auth', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'pipeline_logs', type_='foreignkey')
    op.create_foreign_key(op.f('pipeline_logs_ibfk_1'), 'pipeline_logs', 'chat_details', ['chat_detail_id'], ['id'])
    op.drop_constraint(None, 'otp_reset_password', type_='foreignkey')
    op.create_foreign_key(op.f('otp_reset_password_ibfk_1'), 'otp_reset_password', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'otp_registrasi', type_='foreignkey')
    op.create_foreign_key(op.f('otp_registrasi_ibfk_1'), 'otp_registrasi', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.create_foreign_key(op.f('chats_ibfk_1'), 'chats', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'chat_details', type_='foreignkey')
    op.create_foreign_key(op.f('chat_details_ibfk_1'), 'chat_details', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###
