"""adding change email schema

Revision ID: 964146876a6e
Revises: 49538283cfb5
Create Date: 2026-03-23 12:46:56.480829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964146876a6e'
down_revision: Union[str, Sequence[str], None] = '49538283cfb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_change_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=False),
    sa.Column('otp_expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('is_invalidated', sa.Boolean(), nullable=False),
    sa.Column('request_count_today', sa.Integer(), nullable=False),
    sa.Column('change_token', sa.String(length=255), nullable=True),
    sa.Column('change_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('change_token')
    )
    op.create_index(op.f('ix_otp_change_email_id'), 'otp_change_email', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_change_email_id'), table_name='otp_change_email')
    op.drop_table('otp_change_email')
    # ### end Alembic commands ###
