"""updating sse to backend

Revision ID: cd94a715ea0d
Revises: 964146876a6e
Create Date: 2026-03-24 11:44:06.048210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd94a715ea0d'
down_revision: Union[str, Sequence[str], None] = '964146876a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_details', sa.Column('processing_status', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_details', 'processing_status')
    # ### end Alembic commands ###
