"""adding access token column

Revision ID: f5a8b1e060cb
Revises: 
Create Date: 2026-03-04 14:17:47.097471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f5a8b1e060cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'title',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('users', sa.Column('access_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('access_token_expires_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'profile_image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_id', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('users', 'access_token_expires_at')
    op.drop_column('users', 'access_token')
    op.alter_column('chats', 'title',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###
